{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.erik_flutter_host_module",
    "module": "flutter_release",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "com.eccentric.erik_flutter",
          "module": "erik_flutter_sdk_release",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.1.aar",
          "url": "flutter_release-1.0.1.aar",
          "size": 2050264,
          "sha512": "3a08dcb14d7b4db96842d8b8cd726efe844af01c22f93ba554d0eb40069ffd298a3f6589e3b4a92fbd13ce16e333e237cc427614fe83acc231ba91bca115b22e",
          "sha256": "61d2e56fcf9a963ab7add609bb77780015d979676df9a07dc454f746f682c0df",
          "sha1": "d7be86b081cfbabc3e6b82f9dbfe1ff8959a6635",
          "md5": "fc1d068d399f5ef3e1938cb8cd6e3ec7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "com.eccentric.erik_flutter",
          "module": "erik_flutter_sdk_release",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.1.aar",
          "url": "flutter_release-1.0.1.aar",
          "size": 2050264,
          "sha512": "3a08dcb14d7b4db96842d8b8cd726efe844af01c22f93ba554d0eb40069ffd298a3f6589e3b4a92fbd13ce16e333e237cc427614fe83acc231ba91bca115b22e",
          "sha256": "61d2e56fcf9a963ab7add609bb77780015d979676df9a07dc454f746f682c0df",
          "sha1": "d7be86b081cfbabc3e6b82f9dbfe1ff8959a6635",
          "md5": "fc1d068d399f5ef3e1938cb8cd6e3ec7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0.1-sources.jar",
          "url": "flutter_release-1.0.1-sources.jar",
          "size": 1110,
          "sha512": "41fa8ed2963d32d657a1ab05ec34415e2d89639d226a11c613b52953f2c018a333fa4317f182c8537fa9f5faca97c2b9456daaaddc41cd454fb38515294b26c6",
          "sha256": "e856695a05ef195df8aa633165fb182de3c375cd37d84f4e51fb4b4dcbeed766",
          "sha1": "8f1bb4aa5ba0219b53517cd90f66354bd90255aa",
          "md5": "1d032d3cb167af72cf111d2aa72067fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0.1-javadoc.jar",
          "url": "flutter_release-1.0.1-javadoc.jar",
          "size": 261619,
          "sha512": "7ab0b3b2926e2fa13a31f88f990e64dfa320ebf1d1ecdbc9baf7bac4fbb48e4d00a4ae12704c4c56f14303e142d9dfa183700d594deb2e82cfacb91849651a84",
          "sha256": "8e7c4e97400d52f2b8ef03c18fe28c54f359c9615979b9aa272615fb64ed26cd",
          "sha1": "7e9738e646ade37ffcd7b833488f338ff4c80bb5",
          "md5": "42f4f2c9a78454ff5c250538251f8996"
        }
      ]
    }
  ]
}
