{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eccentric",
    "module": "erik-android-remote-sdk",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.eccentric",
          "module": "erik-android-api",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik-android-remote-sdk-1.0.4.aar",
          "url": "erik-android-remote-sdk-1.0.4.aar",
          "size": 65562,
          "sha512": "214f0ec1dd06c4869d266c6d11698757c38a0c45267c5cbb77274e07ebc039f9c67375dbd07688f72cde94814c540301af4af4b7db30ce31f41461e98cc8e745",
          "sha256": "d7a326d913eb4545ed45006638b07862c556e0e18ae101736838386d4982cdac",
          "sha1": "6ce14206e8f69ca9e5917ce8957587e93e91e163",
          "md5": "d9b9dde084405a7dca5c1b0c1485cd45"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.eccentric",
          "module": "erik-android-api",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik-android-remote-sdk-1.0.4.aar",
          "url": "erik-android-remote-sdk-1.0.4.aar",
          "size": 65562,
          "sha512": "214f0ec1dd06c4869d266c6d11698757c38a0c45267c5cbb77274e07ebc039f9c67375dbd07688f72cde94814c540301af4af4b7db30ce31f41461e98cc8e745",
          "sha256": "d7a326d913eb4545ed45006638b07862c556e0e18ae101736838386d4982cdac",
          "sha1": "6ce14206e8f69ca9e5917ce8957587e93e91e163",
          "md5": "d9b9dde084405a7dca5c1b0c1485cd45"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "erik-android-remote-sdk-1.0.4-sources.jar",
          "url": "erik-android-remote-sdk-1.0.4-sources.jar",
          "size": 11426,
          "sha512": "302a894d1a275f0e8c47773d4a3c9a423bedde9a33e5b2aee790e7b8aec34b9599d0bcdb432c16c20ed3bd66b7eaaf45644a5422dee45096d3946ac294e4515b",
          "sha256": "714a6ab583988190349ea69d12110be8ff99a28036b1a011467f3b2b50532673",
          "sha1": "21c4b9a3896aa09682be9c80c7266e6c0cfe70e8",
          "md5": "be4e7325b41a4b80a8952a28458f9215"
        }
      ]
    }
  ]
}
