{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eccentric.erik_flutter",
    "module": "erik_flutter_sdk_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik_flutter_sdk_release-1.0.aar",
          "url": "erik_flutter_sdk_release-1.0.aar",
          "size": 26147726,
          "sha512": "580fae2adbe7acaeff0791a6d337082e8d9a05a638ffadb3ddf4226cac60ea7318ab37d73bcd26a6aa24bc0b19ebfccf18ce1a053fdef157e3c69cd9c2f89cb3",
          "sha256": "057d09ec96e04a43bb46849f19801b066e756344a9080b0f09015a7de3461869",
          "sha1": "c97578eb43cb16f777bc7a0455700487d102b565",
          "md5": "295fb52ade2fe4cb808764ecf07d6fd1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.github.suhailpatel49",
          "module": "panoramagl",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik_flutter_sdk_release-1.0.aar",
          "url": "erik_flutter_sdk_release-1.0.aar",
          "size": 26147726,
          "sha512": "580fae2adbe7acaeff0791a6d337082e8d9a05a638ffadb3ddf4226cac60ea7318ab37d73bcd26a6aa24bc0b19ebfccf18ce1a053fdef157e3c69cd9c2f89cb3",
          "sha256": "057d09ec96e04a43bb46849f19801b066e756344a9080b0f09015a7de3461869",
          "sha1": "c97578eb43cb16f777bc7a0455700487d102b565",
          "md5": "295fb52ade2fe4cb808764ecf07d6fd1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "erik_flutter_sdk_release-1.0-sources.jar",
          "url": "erik_flutter_sdk_release-1.0-sources.jar",
          "size": 9965,
          "sha512": "4886a4b7b5ff8cd65d37b32946d31f75735befce4a25d3a55010bfe7b614374fd0f3ab19c4a8203689f481dec7e2ac060a8b22151c02dfe023c3897a0e5ff68e",
          "sha256": "79cad8e08d360a71143655752d5117409ac81acb46a481410d57fef64bf145fd",
          "sha1": "c5bc821c4f7bc35d78074a02723f0bfb592e5282",
          "md5": "5e9d073634b9ff8e1c0a0cf87a49c217"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "erik_flutter_sdk_release-1.0-javadoc.jar",
          "url": "erik_flutter_sdk_release-1.0-javadoc.jar",
          "size": 324276,
          "sha512": "9920751460ddaaee75c045c644c327984016751321d2f320517b675c96f36cabefadd19ea61eabb042dd730119fb33a03682c55b9e5172949c7b004ae6e779ea",
          "sha256": "9076d66db0dc8ccee5d45f5725c95ad3e44ac10b9078d8aad125055062a61fdb",
          "sha1": "a556e1e2d046de2a5188abe41e02a01a5097ae1a",
          "md5": "52316320a07c417d9e4d3838e4ed7a25"
        }
      ]
    }
  ]
}
