{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eccentric.erik_flutter",
    "module": "erik_flutter_sdk_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik_flutter_sdk_release-1.0.aar",
          "url": "erik_flutter_sdk_release-1.0.aar",
          "size": 26145218,
          "sha512": "a238fa54be7af296d6534c98351577b5889a2c3a6aa1807f77116100a73cbf3b9b708935d728f40bfc0ecc383b3b6f893467b07340953158a433d2b777339363",
          "sha256": "d29b443e33d4f2563e3abd1779c9dd2c91d993256dd65d0db1e7bcf6253e7e5a",
          "sha1": "50b6ba9838162ba8786b906125593dbc96bfab03",
          "md5": "a9ad4f0847a74888450ba77ef5d0c405"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.github.hannesa2",
          "module": "panoramagl",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik_flutter_sdk_release-1.0.aar",
          "url": "erik_flutter_sdk_release-1.0.aar",
          "size": 26145218,
          "sha512": "a238fa54be7af296d6534c98351577b5889a2c3a6aa1807f77116100a73cbf3b9b708935d728f40bfc0ecc383b3b6f893467b07340953158a433d2b777339363",
          "sha256": "d29b443e33d4f2563e3abd1779c9dd2c91d993256dd65d0db1e7bcf6253e7e5a",
          "sha1": "50b6ba9838162ba8786b906125593dbc96bfab03",
          "md5": "a9ad4f0847a74888450ba77ef5d0c405"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "erik_flutter_sdk_release-1.0-sources.jar",
          "url": "erik_flutter_sdk_release-1.0-sources.jar",
          "size": 9601,
          "sha512": "5a59397fd4c375ae5f3a2522cdd1a6857ceee66ea926cdf1c9496d576a4f43d3c0724d45ea22ca635181b5d0898f4618564e3c8a0ebb175e965b0d0701c38786",
          "sha256": "a7ef32121bba7e58dc39dcd78d97c58b2483d296aeae055ed575f13ffdfe6dab",
          "sha1": "9ddb9bc5f7092c32c00ff4df6215f28681b8d901",
          "md5": "e6ebe4436823aa904cdf9cf1259bdbdb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "erik_flutter_sdk_release-1.0-javadoc.jar",
          "url": "erik_flutter_sdk_release-1.0-javadoc.jar",
          "size": 324276,
          "sha512": "9920751460ddaaee75c045c644c327984016751321d2f320517b675c96f36cabefadd19ea61eabb042dd730119fb33a03682c55b9e5172949c7b004ae6e779ea",
          "sha256": "9076d66db0dc8ccee5d45f5725c95ad3e44ac10b9078d8aad125055062a61fdb",
          "sha1": "a556e1e2d046de2a5188abe41e02a01a5097ae1a",
          "md5": "52316320a07c417d9e4d3838e4ed7a25"
        }
      ]
    }
  ]
}
