{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eccentric.erik_flutter",
    "module": "erik_flutter_sdk_profile",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik_flutter_sdk_profile-1.0.1.aar",
          "url": "erik_flutter_sdk_profile-1.0.1.aar",
          "size": 15855737,
          "sha512": "7ef97b8433bca503535bd94ecc17f8964e55aa8fa3e1c8e5b6f586f72d3d6425675e633ba2f8f97ce4f9f2e6bf11a8ebb47e6f8ab798d8d7948cb8df12b5b580",
          "sha256": "c9de7ce57261c756c643f22122e8764e67369d0630c024d90f45e846ee7ff27c",
          "sha1": "edd8c2c78041eb416738355ee43337d5c6772282",
          "md5": "aa795eac65eba3258e3dc7f6ac31a455"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.github.suhailpatel49",
          "module": "panoramagl",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik_flutter_sdk_profile-1.0.1.aar",
          "url": "erik_flutter_sdk_profile-1.0.1.aar",
          "size": 15855737,
          "sha512": "7ef97b8433bca503535bd94ecc17f8964e55aa8fa3e1c8e5b6f586f72d3d6425675e633ba2f8f97ce4f9f2e6bf11a8ebb47e6f8ab798d8d7948cb8df12b5b580",
          "sha256": "c9de7ce57261c756c643f22122e8764e67369d0630c024d90f45e846ee7ff27c",
          "sha1": "edd8c2c78041eb416738355ee43337d5c6772282",
          "md5": "aa795eac65eba3258e3dc7f6ac31a455"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "erik_flutter_sdk_profile-1.0.1-sources.jar",
          "url": "erik_flutter_sdk_profile-1.0.1-sources.jar",
          "size": 9965,
          "sha512": "00b9aa3a94ab0d47b880c5de12d01bc0c224b0933cfba26f1e1ba0a876795de08ceecbb0b2c82476c4b3917e41b2126bf7f506e5238add92e054f1e9667f987e",
          "sha256": "c6123aca3ddaa3a320b40f484c578ce04962ac76bccaf36633cf8a1f7288fb68",
          "sha1": "d2cd899f56423661f3557db081f8593e260af67b",
          "md5": "193d5a5c43a79fb96fa8f78e3ff31fb7"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "erik_flutter_sdk_profile-1.0.1-javadoc.jar",
          "url": "erik_flutter_sdk_profile-1.0.1-javadoc.jar",
          "size": 324298,
          "sha512": "fe7fca7c4ad54f08384ccf92a8fc84e204c9ac96ee6e383b01305f879e2684644c3e69c75f790d575a6b6570cf7a1b752e4099e14fb26462e6619351447fab51",
          "sha256": "2cd68947f1e7ff56eebe121f28fa21d1e58d753e95d8b18e67c6897436d94ea5",
          "sha1": "1bc068d95bb4dd7a2e3bc9a7890c8d513ba9e9ec",
          "md5": "d4e2fb04ed0bb937fa1545fc3aaa2cba"
        }
      ]
    }
  ]
}
