{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eccentric",
    "module": "erik-android-sdk",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.eccentric",
          "module": "erik-android-api",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.github.suhailpatel49",
          "module": "panoramagl",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik-android-sdk-2.0.0.aar",
          "url": "erik-android-sdk-2.0.0.aar",
          "size": 215619,
          "sha512": "05467825c4917e5d2d1808ebb1d6e6752c2628f69d61afc25caf127781d4ec5ae90ff30cfb0bbc3399033bf0770814b086f0982a5e18346ee7d90669f353ed6e",
          "sha256": "175e3f3217691a90c5c9c496c9be6709ec969e3d14b536327d2162eeda018ffd",
          "sha1": "52577542da9060a020325fcaac03c3a139b2bc25",
          "md5": "f069e635f3f4e9f5cfaa767e74e8d941"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.eccentric",
          "module": "erik-android-api",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.github.suhailpatel49",
          "module": "panoramagl",
          "version": {
            "requires": "1.14.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik-android-sdk-2.0.0.aar",
          "url": "erik-android-sdk-2.0.0.aar",
          "size": 215619,
          "sha512": "05467825c4917e5d2d1808ebb1d6e6752c2628f69d61afc25caf127781d4ec5ae90ff30cfb0bbc3399033bf0770814b086f0982a5e18346ee7d90669f353ed6e",
          "sha256": "175e3f3217691a90c5c9c496c9be6709ec969e3d14b536327d2162eeda018ffd",
          "sha1": "52577542da9060a020325fcaac03c3a139b2bc25",
          "md5": "f069e635f3f4e9f5cfaa767e74e8d941"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "erik-android-sdk-2.0.0-sources.jar",
          "url": "erik-android-sdk-2.0.0-sources.jar",
          "size": 38822,
          "sha512": "b5fc7ed4f3769be5ebab9bace0ac93b590806af08a886e9dfad3a455655cadc2503a0d30df222ddd2cf61ced91c0f8a4264332b073f7da2db760f1c002c0718c",
          "sha256": "e0aba3e39c4acde3f3aec97cc815081b1c5f09b7e1041f6c672d7c1dea987a40",
          "sha1": "7bb364d7e4a4edaaf23ab5a734444af5f2970be2",
          "md5": "97fdce00c750f0cbe888bec001809606"
        }
      ]
    }
  ]
}
