{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eccentric",
    "module": "erik-android-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.github.suhailpatel49",
          "module": "panoramagl",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik-android-sdk-1.0.0.aar",
          "url": "erik-android-sdk-1.0.0.aar",
          "size": 15839820,
          "sha512": "71609b0973361f728a32d6c212b42ed035c20d19cf169f94ac811e8d1d51aefc226e7a685a709574ec26f8fedfef4e174d7b2d775ed8ed3ffd1bd137547d14ab",
          "sha256": "f98243dede79bac4d58823c88799486858d83a0a908a446bf3b607710ffd3533",
          "sha1": "129a90d5f5852cf2270caf7854d7d8c7c8443f77",
          "md5": "dbcdae8c64056c191efeb13bc94d8cec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.github.suhailpatel49",
          "module": "panoramagl",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik-android-sdk-1.0.0.aar",
          "url": "erik-android-sdk-1.0.0.aar",
          "size": 15839820,
          "sha512": "71609b0973361f728a32d6c212b42ed035c20d19cf169f94ac811e8d1d51aefc226e7a685a709574ec26f8fedfef4e174d7b2d775ed8ed3ffd1bd137547d14ab",
          "sha256": "f98243dede79bac4d58823c88799486858d83a0a908a446bf3b607710ffd3533",
          "sha1": "129a90d5f5852cf2270caf7854d7d8c7c8443f77",
          "md5": "dbcdae8c64056c191efeb13bc94d8cec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "erik-android-sdk-1.0.0-sources.jar",
          "url": "erik-android-sdk-1.0.0-sources.jar",
          "size": 6396,
          "sha512": "a0c58b90bf8e2e7583bed7536110728040d7e610d9e9c3c7723c9161dde01794d447828bf8090558e0e01e0b6a21208a476b9717d6c938727d316be974db637a",
          "sha256": "569f0c1dc00d3353c29d441d027794430c9eaade5bf0de224ef5f638d68be070",
          "sha1": "a4bf229552f2c5418c39ab1ceddbf2921fec255b",
          "md5": "e58fdf6b7175d51cfe4e275e7d1b449b"
        }
      ]
    }
  ]
}
