{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eccentric.erik_flutter",
    "module": "erik_flutter_sdk_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik_flutter_sdk_profile-1.0.aar",
          "url": "erik_flutter_sdk_profile-1.0.aar",
          "size": 26149960,
          "sha512": "6fa3ef7bcbe6095b0eb45d6ae3dc036d091a7ca6b2daf5af9894669250441a90459bf02f2f5a61a28d7828d866b41c219e74441d45a8c27a997bc7ddcb309aef",
          "sha256": "e58d268a08398bf9cd939183b8fa79ae227e4900ca6e21fac7a856aa0668c641",
          "sha1": "b830d2329058f5ab335729f65fd785ba4c52a355",
          "md5": "fb6057e654855a25bc14856fb98037b5"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.github.suhailpatel49",
          "module": "panoramagl",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik_flutter_sdk_profile-1.0.aar",
          "url": "erik_flutter_sdk_profile-1.0.aar",
          "size": 26149960,
          "sha512": "6fa3ef7bcbe6095b0eb45d6ae3dc036d091a7ca6b2daf5af9894669250441a90459bf02f2f5a61a28d7828d866b41c219e74441d45a8c27a997bc7ddcb309aef",
          "sha256": "e58d268a08398bf9cd939183b8fa79ae227e4900ca6e21fac7a856aa0668c641",
          "sha1": "b830d2329058f5ab335729f65fd785ba4c52a355",
          "md5": "fb6057e654855a25bc14856fb98037b5"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "erik_flutter_sdk_profile-1.0-sources.jar",
          "url": "erik_flutter_sdk_profile-1.0-sources.jar",
          "size": 9965,
          "sha512": "00b9aa3a94ab0d47b880c5de12d01bc0c224b0933cfba26f1e1ba0a876795de08ceecbb0b2c82476c4b3917e41b2126bf7f506e5238add92e054f1e9667f987e",
          "sha256": "c6123aca3ddaa3a320b40f484c578ce04962ac76bccaf36633cf8a1f7288fb68",
          "sha1": "d2cd899f56423661f3557db081f8593e260af67b",
          "md5": "193d5a5c43a79fb96fa8f78e3ff31fb7"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "erik_flutter_sdk_profile-1.0-javadoc.jar",
          "url": "erik_flutter_sdk_profile-1.0-javadoc.jar",
          "size": 324276,
          "sha512": "9920751460ddaaee75c045c644c327984016751321d2f320517b675c96f36cabefadd19ea61eabb042dd730119fb33a03682c55b9e5172949c7b004ae6e779ea",
          "sha256": "9076d66db0dc8ccee5d45f5725c95ad3e44ac10b9078d8aad125055062a61fdb",
          "sha1": "a556e1e2d046de2a5188abe41e02a01a5097ae1a",
          "md5": "52316320a07c417d9e4d3838e4ed7a25"
        }
      ]
    }
  ]
}
