{
  "formatVersion": "1.1",
  "component": {
    "group": "com.eccentric.erik_flutter",
    "module": "erik_flutter_sdk_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik_flutter_sdk_debug-1.0.aar",
          "url": "erik_flutter_sdk_debug-1.0.aar",
          "size": 26149924,
          "sha512": "588471f03a0b39f0b4fbb0204ee8f829c32170f922763329c6f3b50934019306972c76fc55690122731d2fac4e2ae80f413d3308edc77373530cc4f75b546cbe",
          "sha256": "bc1e64aa3b839f45b1304ef61a7020e7a6739a93a715b1a4bcc9c948abcbb047",
          "sha1": "946bcb01e888e38410e0c2033e12153ed450b7a2",
          "md5": "ce49828cb0454b6eb07ff809b2ad79f0"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.github.suhailpatel49",
          "module": "panoramagl",
          "version": {
            "requires": "1.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "erik_flutter_sdk_debug-1.0.aar",
          "url": "erik_flutter_sdk_debug-1.0.aar",
          "size": 26149924,
          "sha512": "588471f03a0b39f0b4fbb0204ee8f829c32170f922763329c6f3b50934019306972c76fc55690122731d2fac4e2ae80f413d3308edc77373530cc4f75b546cbe",
          "sha256": "bc1e64aa3b839f45b1304ef61a7020e7a6739a93a715b1a4bcc9c948abcbb047",
          "sha1": "946bcb01e888e38410e0c2033e12153ed450b7a2",
          "md5": "ce49828cb0454b6eb07ff809b2ad79f0"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "erik_flutter_sdk_debug-1.0-sources.jar",
          "url": "erik_flutter_sdk_debug-1.0-sources.jar",
          "size": 9965,
          "sha512": "00b9aa3a94ab0d47b880c5de12d01bc0c224b0933cfba26f1e1ba0a876795de08ceecbb0b2c82476c4b3917e41b2126bf7f506e5238add92e054f1e9667f987e",
          "sha256": "c6123aca3ddaa3a320b40f484c578ce04962ac76bccaf36633cf8a1f7288fb68",
          "sha1": "d2cd899f56423661f3557db081f8593e260af67b",
          "md5": "193d5a5c43a79fb96fa8f78e3ff31fb7"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "erik_flutter_sdk_debug-1.0-javadoc.jar",
          "url": "erik_flutter_sdk_debug-1.0-javadoc.jar",
          "size": 324276,
          "sha512": "9920751460ddaaee75c045c644c327984016751321d2f320517b675c96f36cabefadd19ea61eabb042dd730119fb33a03682c55b9e5172949c7b004ae6e779ea",
          "sha256": "9076d66db0dc8ccee5d45f5725c95ad3e44ac10b9078d8aad125055062a61fdb",
          "sha1": "a556e1e2d046de2a5188abe41e02a01a5097ae1a",
          "md5": "52316320a07c417d9e4d3838e4ed7a25"
        }
      ]
    }
  ]
}
